# Copyright 2024-2025 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.

########################
# Application Deployment
########################

# Board IP address
ipAddress=<board_ip>
# Board port, default port is 4001
port=4001

######################
# Kernel Configuration
######################

# Default kernel fetched as a module dependency
kernelGroup=com.microej.kernel
kernelModule=NXP-MIMXRT1170-3_0_0_GCC_GREEN
kernelVersion=2.1.1
